version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: hill-postgres
    environment:
      POSTGRES_USER: gamemaster
      POSTGRES_PASSWORD: dev_password
      POSTGRES_DB: gamemaster_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U gamemaster"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local

